### ISSUE TITLE
big map sometimes not properly indexed

### ISSUE THREAD

**Issue by martinpospech** [baking-bad/bcdhub#518]
A big map seems empty on BCD, but actually there is a value in it.

```
./tezos-client -E https://delphinet.smartpy.io/ get element exprvJjS3U82iRbCaBdX6rK3Q8HH34KtHrWrjdWs5qqcFUGrGCH5dP of big map 79078
```

https://better-call.dev/delphinet/big_map/79078/keys

The contract was created in an internal call and the maps were changed in another internal call, in the same transaction.

**Comment by RomanSerikov** [comment]
Hi! Can u provide a contract address and operation hash, so we can investigate this issue?
