### ISSUE TITLE
Offset not working for search

### ISSUE THREAD

**Issue by w4ll3** [baking-bad/bcdhub#553]
The offset parameter is not working for the `/v1/search` endpoint, regardless of the value it always return the same results.

An example is [this](https://api.better-call.dev/v1/search?q=tz1NQtDQea6ngpGwA9nwbbPpAUe5mGraiajd&i=contract&n=edo2net&g=0&s=0&o=40)

**Comment by aopoltorzhicky** [comment]
Thank you for the issue. It fixed in #555. We deliver fix to production asap.

**Comment by aopoltorzhicky** [comment]
Fixed. You can test it! =)
