### ISSUE TITLE
Contract Fork not working.

### ISSUE THREAD

**Issue by sebuhbitcoin** [baking-bad/bcdhub#710]
Failed to load resource: the server responded with a status of 400 (Bad Request)

I am having an issue with using the fork feature.

I am forking this contract. https://better-call.dev/mainnet/KT1T8TFtJjhChvniW7deGyKL7kkKearqr8uE/fork

All the data is inputted correctly to create the fork. I notice that "Granadanet" has been added, When I use templewallet it keeps failing, when i click raw JSON, it says "network" selection isnt correct.

Key: 'forkRequest.Network' Error:Field validation for 'Network' failed on the 'network' tag 

Seems line 220 in tryacatch.js is where the issue is according to my console log.

webpack://./node_modules/@sentry/browser/esm/integrations/trycatch.js. 

I am not sure what i am doing wrong, i have tried two different browsers now, tried forking a different contract, same issue pretty much.

Please fix it when you can. If you need more logs just let me know ill try to help with that.

Thanks,

Sebuh

**Comment by aopoltorzhicky** [comment]
Thanks for issue. We fixed it.
