### ISSUE TITLE
Add specific token ID to URL for direct linking

### ISSUE THREAD

**Issue by clcmusic** [baking-bad/bcdhub#749]
Would be great to link directly to a specific token ID, so that end users on a marketplace can go directly to a page on BCD to verify the token is on the blockchain.

Ex: https://minterpop.com/object/0
See "View on Blockchain" currently links to https://better-call.dev/mainnet/KT1AaaBSo5AE6Eo8fpEN5xhCD4w3kHStafxk/tokens

The particular token in question has:
 - Title: The Brand
 - Token ID: 0

If URL could end in /{token_id} then direct links could be added.

For the above example the URL would be: https://better-call.dev/mainnet/KT1AaaBSo5AE6Eo8fpEN5xhCD4w3kHStafxk/tokens/0

**Comment by clcmusic** [comment]
If this functionality already is possible and it needs to be added to front end, I can repost on that repo

**Comment by m-kus** [comment]
Thanks for highlighting that @clcmusic ! This is a front end task indeed, will schedule for the next release
