### ISSUE TITLE
Minter missing from token metadata

### ISSUE THREAD

**Issue by 852Kerfunkle** [baking-bad/bcdhub#809]
The _minter_ field (as proposed by TZIP-21, Rich Metadata: https://tzip.tezosagora.org/proposal/tzip-21/#minter-string-format-tzaddress) is missing from the token information returned by bcdhub.

Thanks.

**Comment by 852Kerfunkle** [comment]
Sorry I wasn't clear. To elaborate, in account token balances.

It would be quite useful to have it in there.

**Comment by aopoltorzhicky** [comment]
Thanks for the issue. We fixed it in [this PR](https://github.com/baking-bad/bcdhub/pull/811). The fix will be in the next release.

**Comment by 852Kerfunkle** [comment]
Awesome! Thank you!
